sudo: required
dist: trusty
language: node_js
node_js:
  - 0.12
  - 4
  - 6
  - stable
env:
  - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.7/ubuntu/trusty/riak_2.0.7-1_amd64.deb
  - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.2/2.2.0/ubuntu/trusty/riak_2.2.0-1_amd64.deb
before_script:
  - sudo ./tools/travis-ci/riak-install -i -d "$RIAK_DOWNLOAD_URL"
  - sudo ./tools/setup-riak -s
script:
  - sudo riak-admin security disable
  - make test
  - sudo riak-admin security enable
  - make security-test
notifications:
  slack:
    secure: DatOW6e8FqaZmvxcHw+zZ/ku3wMWZ7eoWmqzhu4Wwf4tgC9L//jy4kj2kJx3gktTMPj3rt6eqw9+j7XOjaSFYD8K+BFh/39ORz6G89/Q3WtoK2OsiREtdskLf1qTku7euvXbwhsVno9AWz2AW+idYQj7WxjUKB4TcYn3B4Od3NU=
